name: Create Release and Upload Files

on:
  # Trigger the workflow when a new tag is pushed
  push:
    tags:
      - 'v*'  # Matches any tag that starts with 'v', e.g., 'v1.0.0'

permissions:
  contents: write  # Grant write permission for contents to create releases

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js environment to build the project
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use Node.js version 18 (or any version your project requires)

      # Install dependencies using Yarn
      - name: Install dependencies
        run: yarn install

      # Build the project (this will create the files in the dist/ folder)
      - name: Build project using Vite
        run: yarn build

      # Create GitHub Release using the tag
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}  # Use the tag name that triggered the workflow
          release_name: Release ${{ github.ref_name }}  # Name the release after the tag
          body: |
            Automatic release for version ${{ github.ref_name }}.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token to authenticate

      # Upload the contents of the dist/ folder to the release
      - name: Upload files to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/gms2.api.js  # Path to the main file you want to upload
          asset_name: gms2.api.js         # Name that will appear in the release
          asset_content_type: application/javascript  # File type (adjust if necessary)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


